### PR TITLE
Added fundamental segmentation.

### PR DESCRIPTION
**Pull request by tresoldi**
Adds fundamental segmentation to the dataset. Almost all the errors (most of them stemming from the transcription of glottalic consonants) can be later solved by an orthographic profile, but we need to decide how to report the tones (the best alternative is probably the slash notation, so that "ê" becomes "e51/e").

A list of string replacements covers most of the errors and indicates the type of sounds that should be accounted/decided for in an orthographic profile.

### CODE REVIEW

**Comment by LinguList** [comment]
> slash notation: e51/e

Actually, the rule is "source/target", so the item before the slash is exactly what you find in the source. so it should be:

> è/e

as simple as that.

**Comment by LinguList** [comment]
Ah, and I'd say it is as simple as quickly going through the profile and making some quick guesses. We can't do this completely right, but the profile is not that long, so one could make a reasonable guess as to the phonetics of the data. As far as I understand, you don't use the profile here, right?

**Comment by tresoldi** [comment]
I mistyped the example, the slash notation is not currently used.

And no, I am not using a profile: there is a hard-coded list of replacements which are those with no guess, just standard notation problems (such as long vowels, etc.). A profile should indeed be very simple, I can replace the shortcut in the code and provide a full profile if desired.

**Comment by LinguList** [comment]
[orthography.txt](https://github.com/lexibank/kraftchadic/files/2572622/orthography.txt)
this is the one we have, automated from lingpy, it contains 500 lines, so about 30 minutes to go through, but I think this is easier than doing it inside the code.

**Comment by tresoldi** [comment]
Ok, I'll replace the code with a profile.

**Comment by tresoldi** [comment]
The last commit adds an orthographic profile; the results should be acceptable for a first pass with no contextual profiles.

The only language which still has many problems is Gudu, as in the source it is transcribed with a unique (and, actually, closest to proper IPA) notation for vowel length; this can later be fixed by accounting for all the vowels in Gudu, but as I'd have questions on the interplay with diphthongs and tones in the language I decided to leave it as it is (there is almost no material on the language on-line).

For all other cases, a review of the bibliography and source are likely necessary; information on the phonology and orthography of Hausa should be enough for most cases.

**Pull request closed without merging**
